spring.application.name=user-service
server.port=8081

# MySQL Configuration
spring.datasource.url=jdbc:mysql://mysql:3306/bankdb

spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

#Swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

logging.level.root=INFO
logging.level.org.springframework=ERROR
logging.level.org.hibernate.SQL=ERROR
logging.level.feign=ERROR

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${HOSTNAME}
